In [1]:
import pandas as pd
from datetime import timedelta

In [2]:
dtypes = {'id':'uint32', 'item_nbr':'int32', 'store_nbr':'int8', 'unit_sales':'float32'}

In [3]:
train = pd.read_csv('../train.csv/train.csv', usecols=[1,2,3,4], dtype=dtypes, parse_dates=['date'],
                    skiprows=range(1, 86672217) #Skip dates before 2016-08-01
                    )

In [5]:
train.loc[(train.unit_sales<0),'unit_sales'] = 0

In [6]:
train['unit_sales'] =  train['unit_sales'].apply(pd.np.log1p)

In [7]:
train['dow'] = train['date'].dt.dayofweek

In [9]:
ma_dw = train[['item_nbr','store_nbr','dow','unit_sales']].groupby(
        ['item_nbr','store_nbr','dow'])['unit_sales'].mean().to_frame('madw').reset_index()

In [11]:
ma_wk = ma_dw[['item_nbr','store_nbr','madw']].groupby(
        ['store_nbr', 'item_nbr'])['madw'].mean().to_frame('mawk').reset_index()

In [14]:
train.drop('dow',1,inplace=True)

In [16]:
u_dates = train.date.unique()

In [19]:
u_items = train.item_nbr.unique()

In [22]:
u_items.shape

(4036L,)

In [23]:
u_stores = train.store_nbr.unique()

In [25]:
train.set_index(['date', 'store_nbr', 'item_nbr'], inplace=True)

In [27]:
train = train.reindex(
    pd.MultiIndex.from_product(
        (u_dates, u_stores, u_items),
        names=['date','store_nbr','item_nbr']
    )
).reset_index()

In [32]:
del u_dates, u_stores, u_items

train.loc[:, 'unit_sales'].fillna(0, inplace=True) # fill NaNs
lastdate = train.iloc[train.shape[0]-1].date

In [37]:
del tmp,tmpg,train

ma_is['mais']=ma_is.median(axis=1)
ma_is.reset_index(inplace=True)
ma_is.drop(list(ma_is.columns.values)[3:],1,inplace=True)

In [42]:
test = pd.read_csv('../test.csv/test.csv', dtype=dtypes, parse_dates=['date'])

In [44]:
test['dow'] = test['date'].dt.dayofweek
test = pd.merge(test, ma_is, how='left', on=['item_nbr','store_nbr'])
test = pd.merge(test, ma_wk, how='left', on=['item_nbr',''])
test = pd.merge(test, ma_dw, how='left', on=['item_nbr','store_nbr','dow'])

In [45]:
test

,id,date,store_nbr,item_nbr,onpromotion,dow,mais,mawk,madw
0,125497040,2017-08-16,1,96995,False,2,0.126638,0.844024,0.693147
1,125497041,2017-08-16,1,99197,False,2,0.206469,1.010969,0.977616
2,125497042,2017-08-16,1,103501,False,2,0.000000,NaN,NaN
3,125497043,2017-08-16,1,103520,False,2,0.649946,1.114774,1.175135
4,125497044,2017-08-16,1,103665,False,2,1.005429,1.320085,1.282500
5,125497045,2017-08-16,1,105574,False,2,1.619312,1.693974,1.951031
6,125497046,2017-08-16,1,105575,False,2,2.275806,2.258817,2.432405
7,125497047,2017-08-16,1,105576,False,2,0.000000,NaN,NaN
8,125497048,2017-08-16,1,105577,False,2,0.545000,1.022971,1.096418
9,125497049,2017-08-16,1,105693,False,2,0.276514,0.852271,0.939412
10,125497050,2017-08-16,1,105737,False,2,0.647187,1.199824,1.422326
11,125497051,2017-08-16,1,105857,False,2,1.611646,1.610766,1.714712
12,125497052,2017-08-16,1,106716,False,2,1.153162,1.052034,1.141853
13,125497053,2017-08-16,1,108079,False,2,0.382782,0.936147,0.944348
14,125497054,2017-08-16,1,108634,False,2,0.000000,0.788346,0.693147
15,125497055,2017-08-16,1,108696,False,2,0.932404,1.109915,1.125037
16,125497056,2017-08-16,1,108698,False,2,0.693147,1.254247,1.300395
17,125497057,2017-08-16,1,108701,True,2,0.690474,0.957468,1.018947
18,125497058,2017-08-16,1,108786,False,2,1.090199,1.216750,1.339809
19,125497059,2017-08-16,1,108797,True,2,1.218956,1.350242,1.485008
20,125497060,2017-08-16,1,108831,False,2,0.000000,1.587552,NaN
21,125497061,2017-08-16,1,108833,False,2,0.000000,NaN,NaN
22,125497062,2017-08-16,1,108862,False,2,0.465457,0.971370,1.164838
23,125497063,2017-08-16,1,108952,False,2,0.803778,1.017281,1.138442
24,125497064,2017-08-16,1,111223,False,2,1.724460,1.821962,1.878043
25,125497065,2017-08-16,1,111397,False,2,0.497027,1.171076,1.134558
26,125497066,2017-08-16,1,112830,False,2,1.000512,1.215787,1.267737
27,125497067,2017-08-16,1,114778,False,2,1.046400,1.328871,1.308558
28,125497068,2017-08-16,1,114790,True,2,1.177323,1.638673,1.908303
29,125497069,2017-08-16,1,114799,False,2,0.516543,0.968273,1.077932
...,...,...,...,...,...,...,...,...,...
3370434,128867474,2017-08-31,54,2127921,False,3,NaN,NaN,NaN
3370435,128867475,2017-08-31,54,2127992,False,3,NaN,NaN,NaN
3370436,128867476,2017-08-31,54,2128628,False,3,NaN,NaN,NaN
3370437,128867477,2017-08-31,54,2128799,False,3,NaN,NaN,NaN
3370438,128867478,2017-08-31,54,2129334,False,3,NaN,NaN,NaN
3370439,128867479,2017-08-31,54,2129350,False,3,NaN,NaN,NaN
3370440,128867480,2017-08-31,54,2129387,False,3,NaN,NaN,NaN
3370441,128867481,2017-08-31,54,2129515,False,3,NaN,NaN,NaN
3370442,128867482,2017-08-31,54,2129616,False,3,NaN,NaN,NaN
3370443,128867483,2017-08-31,54,2129678,False,3,NaN,NaN,NaN
3370444,128867484,2017-08-31,54,2129786,False,3,NaN,NaN,NaN
3370445,128867485,2017-08-31,54,2129790,False,3,NaN,NaN,NaN
3370446,128867486,2017-08-31,54,2129892,False,3,NaN,NaN,NaN
3370447,128867487,2017-08-31,54,2129994,False,3,NaN,NaN,NaN
3370448,128867488,2017-08-31,54,2130131,False,3,NaN,NaN,NaN
3370449,128867489,2017-08-31,54,2130219,False,3,NaN,NaN,NaN
3370450,128867490,2017-08-31,54,2130265,False,3,NaN,NaN,NaN
3370451,128867491,2017-08-31,54,2130352,False,3,NaN,NaN,NaN
3370452,128867492,2017-08-31,54,2130474,False,3,NaN,NaN,NaN
3370453,128867493,2017-08-31,54,2130521,False,3,NaN,NaN,NaN
3370454,128867494,2017-08-31,54,2130526,False,3,NaN,NaN,NaN
3370455,128867495,2017-08-31,54,2130553,False,3,NaN,NaN,NaN
3370456,128867496,2017-08-31,54,2131010,False,3,NaN,NaN,NaN
3370457,128867497,2017-08-31,54,2131572,False,3,NaN,NaN,NaN
3370458,128867498,2017-08-31,54,2131699,False,3,NaN,NaN,NaN
3370459,128867499,2017-08-31,54,2132163,False,3,NaN,NaN,NaN
3370460,128867500,2017-08-31,54,2132318,False,3,NaN,NaN,NaN
3370461,128867501,2017-08-31,54,2132945,False,3,NaN,NaN,NaN
3370462,128867502,2017-08-31,54,2132957,False,3,NaN,NaN,NaN
3370463,128867503,2017-08-31,54,2134244,False,3,NaN,NaN,NaN

In [46]:
del ma_is, ma_wk, ma_dw

#Forecasting Test
test['unit_sales'] = test.mais 
pos_idx = test['mawk'] > 0
test_pos = test.loc[pos_idx]
test.loc[pos_idx, 'unit_sales'] = test_pos['mais'] * test_pos['madw'] / test_pos['mawk']
test.loc[:, "unit_sales"].fillna(0, inplace=True)
test['unit_sales'] = test['unit_sales'].apply(pd.np.expm1) # restoring unit values

In [47]:
test.loc[test['onpromotion'] == True, 'unit_sales'] *= 1.5

In [48]:
test

,id,date,store_nbr,item_nbr,onpromotion,dow,mais,mawk,madw,unit_sales
0,125497040,2017-08-16,1,96995,False,2,0.126638,0.844024,0.693147,0.109601
1,125497041,2017-08-16,1,99197,False,2,0.206469,1.010969,0.977616,0.220984
2,125497042,2017-08-16,1,103501,False,2,0.000000,NaN,NaN,0.000000
3,125497043,2017-08-16,1,103520,False,2,0.649946,1.114774,1.175135,0.984047
4,125497044,2017-08-16,1,103665,False,2,1.005429,1.320085,1.282500,1.655950
5,125497045,2017-08-16,1,105574,False,2,1.619312,1.693974,1.951031,5.456189
6,125497046,2017-08-16,1,105575,False,2,2.275806,2.258817,2.432405,10.596462
7,125497047,2017-08-16,1,105576,False,2,0.000000,NaN,NaN,0.000000
8,125497048,2017-08-16,1,105577,False,2,0.545000,1.022971,1.096418,0.793431
9,125497049,2017-08-16,1,105693,False,2,0.276514,0.852271,0.939412,0.356336
10,125497050,2017-08-16,1,105737,False,2,0.647187,1.199824,1.422326,1.153740
11,125497051,2017-08-16,1,105857,False,2,1.611646,1.610766,1.714712,4.560278
12,125497052,2017-08-16,1,106716,False,2,1.153162,1.052034,1.141853,2.495987
13,125497053,2017-08-16,1,108079,False,2,0.382782,0.936147,0.944348,0.471284
14,125497054,2017-08-16,1,108634,False,2,0.000000,0.788346,0.693147,0.000000
15,125497055,2017-08-16,1,108696,False,2,0.932404,1.109915,1.125037,1.573091
16,125497056,2017-08-16,1,108698,False,2,0.693147,1.254247,1.300395,1.051662
17,125497057,2017-08-16,1,108701,True,2,0.690474,0.957468,1.018947,1.627627
18,125497058,2017-08-16,1,108786,False,2,1.090199,1.216750,1.339809,2.321642
19,125497059,2017-08-16,1,108797,True,2,1.218956,1.350242,1.485008,4.232107
20,125497060,2017-08-16,1,108831,False,2,0.000000,1.587552,NaN,0.000000
21,125497061,2017-08-16,1,108833,False,2,0.000000,NaN,NaN,0.000000
22,125497062,2017-08-16,1,108862,False,2,0.465457,0.971370,1.164838,0.747459
23,125497063,2017-08-16,1,108952,False,2,0.803778,1.017281,1.138442,1.458400
24,125497064,2017-08-16,1,111223,False,2,1.724460,1.821962,1.878043,4.915287
25,125497065,2017-08-16,1,111397,False,2,0.497027,1.171076,1.134558,0.618545
26,125497066,2017-08-16,1,112830,False,2,1.000512,1.215787,1.267737,1.838467
27,125497067,2017-08-16,1,114778,False,2,1.046400,1.328871,1.308558,1.802201
28,125497068,2017-08-16,1,114790,True,2,1.177323,1.638673,1.908303,4.409184
29,125497069,2017-08-16,1,114799,False,2,0.516543,0.968273,1.077932,0.777205
...,...,...,...,...,...,...,...,...,...,...
3370434,128867474,2017-08-31,54,2127921,False,3,NaN,NaN,NaN,0.000000
3370435,128867475,2017-08-31,54,2127992,False,3,NaN,NaN,NaN,0.000000
3370436,128867476,2017-08-31,54,2128628,False,3,NaN,NaN,NaN,0.000000
3370437,128867477,2017-08-31,54,2128799,False,3,NaN,NaN,NaN,0.000000
3370438,128867478,2017-08-31,54,2129334,False,3,NaN,NaN,NaN,0.000000
3370439,128867479,2017-08-31,54,2129350,False,3,NaN,NaN,NaN,0.000000
3370440,128867480,2017-08-31,54,2129387,False,3,NaN,NaN,NaN,0.000000
3370441,128867481,2017-08-31,54,2129515,False,3,NaN,NaN,NaN,0.000000
3370442,128867482,2017-08-31,54,2129616,False,3,NaN,NaN,NaN,0.000000
3370443,128867483,2017-08-31,54,2129678,False,3,NaN,NaN,NaN,0.000000
3370444,128867484,2017-08-31,54,2129786,False,3,NaN,NaN,NaN,0.000000
3370445,128867485,2017-08-31,54,2129790,False,3,NaN,NaN,NaN,0.000000
3370446,128867486,2017-08-31,54,2129892,False,3,NaN,NaN,NaN,0.000000
3370447,128867487,2017-08-31,54,2129994,False,3,NaN,NaN,NaN,0.000000
3370448,128867488,2017-08-31,54,2130131,False,3,NaN,NaN,NaN,0.000000
3370449,128867489,2017-08-31,54,2130219,False,3,NaN,NaN,NaN,0.000000
3370450,128867490,2017-08-31,54,2130265,False,3,NaN,NaN,NaN,0.000000
3370451,128867491,2017-08-31,54,2130352,False,3,NaN,NaN,NaN,0.000000
3370452,128867492,2017-08-31,54,2130474,False,3,NaN,NaN,NaN,0.000000
3370453,128867493,2017-08-31,54,2130521,False,3,NaN,NaN,NaN,0.000000
3370454,128867494,2017-08-31,54,2130526,False,3,NaN,NaN,NaN,0.000000
3370455,128867495,2017-08-31,54,2130553,False,3,NaN,NaN,NaN,0.000000
3370456,128867496,2017-08-31,54,2131010,False,3,NaN,NaN,NaN,0.000000
3370457,128867497,2017-08-31,54,2131572,False,3,NaN,NaN,NaN,0.000000
3370458,128867498,2017-08-31,54,2131699,False,3,NaN,NaN,NaN,0.000000
3370459,128867499,2017-08-31,54,2132163,False,3,NaN,NaN,NaN,0.000000
3370460,128867500,2017-08-31,54,2132318,False,3,NaN,NaN,NaN,0.000000
3370461,128867501,2017-08-31,54,2132945,False,3,NaN,NaN,NaN,0.000000
3370462,128867502,2017-08-31,54,2132957,False,3,NaN,NaN,NaN,0.000000
3370463,128867503,2017-08-31,54,2134244,False,3,NaN,NaN,NaN,0.000000

In [1]:
from datetime import date, timedelta

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import lightgbm as lgb

In [2]:
df_train = pd.read_csv(
    '../train.csv/train.csv', usecols=[1, 2, 3, 4, 5],
    dtype={'onpromotion': bool},
    converters={'unit_sales': lambda u: np.log1p(
        float(u)) if float(u) > 0 else 0},
    parse_dates=["date"],
    skiprows=range(1, 66458909)  # 2016-01-01
)

df_test = pd.read_csv(
    "../test.csv/test.csv", usecols=[0, 1, 2, 3, 4],
    dtype={'onpromotion': bool},
    parse_dates=["date"]  # , date_parser=parser
).set_index(
    ['store_nbr', 'item_nbr', 'date']
)

In [4]:
items = pd.read_csv(
    "../items.csv/items.csv",
).set_index("item_nbr")

In [5]:
df_2017 = df_train.loc[df_train.date>=pd.datetime(2017,1,1)]

In [7]:
del df_train

In [8]:
promo_2017_train = df_2017.set_index(
    ["store_nbr", "item_nbr", "date"])[["onpromotion"]].unstack(
        level=-1).fillna(False)

In [10]:
promo_2017_train.columns = promo_2017_train.columns.get_level_values(1)

In [12]:
promo_2017_test = df_test[["onpromotion"]].unstack(level=-1).fillna(False)

In [17]:
promo_2017_test = promo_2017_test.reindex(promo_2017_train.index).fillna(False)
promo_2017 = pd.concat([promo_2017_train, promo_2017_test], axis=1)

In [19]:
del promo_2017_test, promo_2017_train

In [20]:
df_2017 = df_2017.set_index(
    ["store_nbr", "item_nbr", "date"])[["unit_sales"]].unstack(
        level=-1).fillna(0)
df_2017.columns = df_2017.columns.get_level_values(1)

In [21]:
items = items.reindex(df_2017.index.get_level_values(1))

In [23]:
def get_timespan(df, dt, minus, periods, freq='D'):
    return df[pd.date_range(dt - timedelta(days=minus), periods=periods, freq=freq)]

In [24]:
def prepare_dataset(t2017, is_train=True):
    X = pd.DataFrame({
        "day_1_2017": get_timespan(df_2017, t2017, 1, 1).values.ravel(),
        "mean_3_2017": get_timespan(df_2017, t2017, 3, 3).mean(axis=1).values,
        "mean_7_2017": get_timespan(df_2017, t2017, 7, 7).mean(axis=1).values,
        "mean_14_2017": get_timespan(df_2017, t2017, 14, 14).mean(axis=1).values,
        "mean_30_2017": get_timespan(df_2017, t2017, 30, 30).mean(axis=1).values,
        "mean_60_2017": get_timespan(df_2017, t2017, 60, 60).mean(axis=1).values,
        "mean_140_2017": get_timespan(df_2017, t2017, 140, 140).mean(axis=1).values,
        "promo_14_2017": get_timespan(promo_2017, t2017, 14, 14).sum(axis=1).values,
        "promo_60_2017": get_timespan(promo_2017, t2017, 60, 60).sum(axis=1).values,
        "promo_140_2017": get_timespan(promo_2017, t2017, 140, 140).sum(axis=1).values
    })
    for i in range(7):
        X['mean_4_dow{}_2017'.format(i)] = get_timespan(df_2017, t2017, 28-i, 4, freq='7D').mean(axis=1).values
        X['mean_20_dow{}_2017'.format(i)] = get_timespan(df_2017, t2017, 140-i, 20, freq='7D').mean(axis=1).values
    for i in range(16):
        X["promo_{}".format(i)] = promo_2017[
            t2017 + timedelta(days=i)].values.astype(np.uint8)
    if is_train:
        y = df_2017[
            pd.date_range(t2017, periods=16)
        ].values
        return X, y
    return X

In [25]:
t2017 = date(2017, 5, 31)
X_l, y_l = [], []
for i in range(6):
    delta = timedelta(days=7 * i)
    X_tmp, y_tmp = prepare_dataset(
        t2017 + delta
    )
    X_l.append(X_tmp)
    y_l.append(y_tmp)
X_train = pd.concat(X_l, axis=0)
y_train = np.concatenate(y_l, axis=0)
del X_l, y_l
X_val, y_val = prepare_dataset(date(2017, 7, 26))
X_test = prepare_dataset(date(2017, 8, 16), is_train=False)

In [33]:
print("Training and predicting models...")
params = {
    'num_leaves': 31,
    'objective': 'regression',
    'min_data_in_leaf': 300,
    'learning_rate': 0.1,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 2,
    'metric': 'l2',
    'num_threads': 4
}

Training and predicting models...

In [34]:
MAX_ROUNDS = 2000
val_pred = []
test_pred = []
cate_vars = []
for i in range(16):
    print("=" * 50)
    print("Step %d" % (i+1))
    print("=" * 50)
    dtrain = lgb.Dataset(
        X_train, label=y_train[:, i],
        categorical_feature=cate_vars,
        weight=pd.concat([items["perishable"]] * 6) * 0.25 + 1
    )
    dval = lgb.Dataset(
        X_val, label=y_val[:, i], reference=dtrain,
        weight=items["perishable"] * 0.25 + 1,
        categorical_feature=cate_vars)
    bst = lgb.train(
        params, dtrain, num_boost_round=MAX_ROUNDS,
        valid_sets=[dtrain, dval], early_stopping_rounds=50, verbose_eval=100
    )
    print("\n".join(("%s: %.2f" % x) for x in sorted(
        zip(X_train.columns, bst.feature_importance("gain")),
        key=lambda x: x[1], reverse=True
    )))
    val_pred.append(bst.predict(
        X_val, num_iteration=bst.best_iteration or MAX_ROUNDS))
    test_pred.append(bst.predict(
        X_test, num_iteration=bst.best_iteration or MAX_ROUNDS))

==================================================
Step 1
==================================================

d:\softwares\Anaconda2\lib\site-packages\lightgbm\basic.py:1027: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')

Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.30165	valid_1's l2: 0.294069
[200]	training's l2: 0.298063	valid_1's l2: 0.292692
[300]	training's l2: 0.29561	valid_1's l2: 0.292274
[400]	training's l2: 0.293648	valid_1's l2: 0.29206
[500]	training's l2: 0.291822	valid_1's l2: 0.291923
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.291822	valid_1's l2: 0.291923
mean_7_2017: 1942372.00
mean_14_2017: 1150857.69
mean_30_2017: 127412.84
promo_0: 103533.42
mean_20_dow0_2017: 80733.01
day_1_2017: 76932.56
mean_3_2017: 71583.75
mean_4_dow0_2017: 58262.28
promo_14_2017: 29372.56
mean_60_2017: 24099.99
promo_7: 9064.66
promo_60_2017: 6791.67
mean_4_dow5_2017: 6429.96
mean_140_2017: 6363.31
mean_20_dow4_2017: 5894.72
promo_140_2017: 5630.61
mean_4_dow6_2017: 5319.77
mean_20_dow2_2017: 3878.68
mean_4_dow2_2017: 3495.79
mean_4_dow3_2017: 2953.13
mean_20_dow1_2017: 2947.08
promo_14: 2812.74
promo_9: 2710.69
mean_4_dow1_2017: 2697.50
mean_4_dow4_2017: 2579.38
mean_20_dow3_2017: 2559.16
mean_20_dow6_2017: 2245.25
mean_20_dow5_2017: 2117.72
promo_15: 1465.14
promo_3: 1396.61
promo_11: 1317.19
promo_13: 1067.82
promo_1: 1017.56
promo_4: 889.50
promo_2: 844.08
promo_12: 390.51
promo_6: 343.30
promo_10: 307.87
promo_5: 157.55
promo_8: 99.11
==================================================
Step 2
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.326544	valid_1's l2: 0.327056
[200]	training's l2: 0.322936	valid_1's l2: 0.325592
[300]	training's l2: 0.32028	valid_1's l2: 0.325042
[400]	training's l2: 0.318042	valid_1's l2: 0.324754
[500]	training's l2: 0.316082	valid_1's l2: 0.324723
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.316082	valid_1's l2: 0.324723
mean_14_2017: 1446336.44
mean_7_2017: 1074487.64
mean_30_2017: 229173.56
mean_20_dow1_2017: 69870.12
mean_60_2017: 63966.13
promo_1: 63098.35
day_1_2017: 39856.72
promo_14_2017: 23522.32
mean_3_2017: 21769.54
mean_4_dow1_2017: 18846.38
promo_60_2017: 6519.83
mean_20_dow2_2017: 6443.72
mean_140_2017: 6118.70
mean_20_dow4_2017: 5474.73
promo_0: 4489.23
mean_4_dow6_2017: 4155.57
promo_140_2017: 4082.67
mean_4_dow0_2017: 3634.40
mean_4_dow2_2017: 3399.25
promo_3: 3283.99
mean_4_dow4_2017: 3150.53
mean_4_dow5_2017: 2895.16
promo_4: 2877.41
mean_4_dow3_2017: 2823.65
mean_20_dow0_2017: 2802.51
mean_20_dow5_2017: 2625.85
mean_20_dow6_2017: 2438.09
mean_20_dow3_2017: 2099.06
promo_5: 1506.78
promo_2: 1418.85
promo_7: 865.33
promo_6: 742.46
promo_14: 525.37
promo_15: 409.75
promo_13: 376.27
promo_11: 375.96
promo_9: 311.79
promo_10: 243.92
promo_12: 212.83
promo_8: 194.15
==================================================
Step 3
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.329268	valid_1's l2: 0.341255
[200]	training's l2: 0.324962	valid_1's l2: 0.33969
[300]	training's l2: 0.322086	valid_1's l2: 0.339206
[400]	training's l2: 0.319635	valid_1's l2: 0.338812
[500]	training's l2: 0.31744	valid_1's l2: 0.33873
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.31744	valid_1's l2: 0.33873
mean_14_2017: 1847554.05
mean_7_2017: 868706.90
mean_30_2017: 233581.16
mean_20_dow2_2017: 225576.85
mean_4_dow2_2017: 218356.82
promo_2: 99763.96
promo_14_2017: 24320.67
mean_3_2017: 22597.30
mean_60_2017: 19265.09
day_1_2017: 11853.61
promo_60_2017: 10139.08
promo_140_2017: 9984.43
mean_20_dow4_2017: 7650.40
mean_4_dow1_2017: 6707.81
promo_9: 6094.94
promo_3: 6025.18
mean_4_dow0_2017: 5112.72
mean_20_dow5_2017: 4750.61
mean_4_dow3_2017: 4615.20
mean_20_dow1_2017: 4235.31
promo_0: 4072.49
mean_140_2017: 3759.12
promo_4: 3738.90
promo_5: 3364.51
promo_7: 3345.95
mean_4_dow6_2017: 3109.28
mean_20_dow0_2017: 3012.78
mean_20_dow3_2017: 2925.96
mean_4_dow4_2017: 2780.38
mean_20_dow6_2017: 2617.01
mean_4_dow5_2017: 2551.40
promo_11: 1626.19
promo_14: 1567.04
promo_15: 1415.84
promo_1: 1253.30
promo_6: 951.30
promo_10: 893.45
promo_12: 703.70
promo_13: 504.37
promo_8: 286.85
==================================================
Step 4
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.352489	valid_1's l2: 0.35448
[200]	training's l2: 0.347907	valid_1's l2: 0.352941
[300]	training's l2: 0.344812	valid_1's l2: 0.352552
Early stopping, best iteration is:
[257]	training's l2: 0.34609	valid_1's l2: 0.352542
mean_14_2017: 2166815.41
mean_7_2017: 666375.93
mean_30_2017: 562097.92
mean_4_dow3_2017: 251047.39
mean_20_dow3_2017: 157208.80
mean_60_2017: 138969.66
promo_3: 75595.48
mean_3_2017: 53462.73
mean_4_dow4_2017: 21324.37
promo_14_2017: 19455.76
promo_60_2017: 6754.88
day_1_2017: 6537.29
mean_140_2017: 5924.98
promo_140_2017: 5766.85
promo_5: 5237.57
promo_4: 4907.44
promo_7: 4294.17
mean_20_dow5_2017: 3917.44
mean_20_dow4_2017: 3777.46
mean_4_dow2_2017: 3691.17
mean_20_dow0_2017: 3426.88
promo_2: 3382.40
promo_0: 2852.93
mean_20_dow6_2017: 2801.09
mean_4_dow0_2017: 2264.78
mean_20_dow2_2017: 2052.38
mean_4_dow6_2017: 1924.19
promo_6: 1862.03
promo_1: 1412.46
mean_20_dow1_2017: 1391.81
mean_4_dow5_2017: 1380.84
mean_4_dow1_2017: 1270.54
promo_14: 1108.88
promo_9: 1041.52
promo_8: 537.32
promo_10: 498.09
promo_15: 417.66
promo_13: 324.43
promo_12: 232.68
promo_11: 199.75
==================================================
Step 5
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.362918	valid_1's l2: 0.357329
[200]	training's l2: 0.357819	valid_1's l2: 0.355714
[300]	training's l2: 0.354367	valid_1's l2: 0.355218
[400]	training's l2: 0.351478	valid_1's l2: 0.354952
[500]	training's l2: 0.349006	valid_1's l2: 0.354863
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.349006	valid_1's l2: 0.354863
mean_14_2017: 1348688.96
mean_4_dow4_2017: 1096604.26
mean_7_2017: 683606.45
mean_30_2017: 540651.11
mean_3_2017: 291014.53
mean_20_dow4_2017: 289141.67
promo_4: 74512.27
mean_60_2017: 31563.66
mean_4_dow3_2017: 21765.00
promo_14_2017: 18753.41
promo_60_2017: 8537.84
promo_3: 7856.11
promo_7: 7322.13
promo_140_2017: 6999.09
promo_5: 6901.18
day_1_2017: 6711.50
mean_20_dow0_2017: 5382.22
mean_20_dow1_2017: 5029.71
mean_20_dow2_2017: 4679.54
promo_6: 4152.18
promo_0: 3951.42
promo_2: 3895.25
mean_4_dow0_2017: 3884.77
mean_140_2017: 3792.99
mean_20_dow3_2017: 3348.26
mean_4_dow5_2017: 3275.54
mean_20_dow6_2017: 3201.57
promo_1: 3182.92
mean_4_dow6_2017: 3097.30
mean_4_dow2_2017: 2842.97
mean_20_dow5_2017: 2791.98
promo_11: 2612.35
mean_4_dow1_2017: 2345.73
promo_14: 1824.19
promo_9: 1232.84
promo_10: 1152.86
promo_13: 875.15
promo_15: 706.16
promo_8: 606.20
promo_12: 568.82
==================================================
Step 6
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.356098	valid_1's l2: 0.361226
[200]	training's l2: 0.351614	valid_1's l2: 0.35965
[300]	training's l2: 0.348705	valid_1's l2: 0.359371
[400]	training's l2: 0.346073	valid_1's l2: 0.359033
[500]	training's l2: 0.343879	valid_1's l2: 0.358907
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.343879	valid_1's l2: 0.358907
mean_14_2017: 1272354.54
mean_30_2017: 1138808.84
mean_7_2017: 335889.20
mean_3_2017: 252924.40
mean_60_2017: 178703.53
mean_20_dow5_2017: 82788.67
promo_5: 79714.40
mean_4_dow5_2017: 67965.64
promo_14_2017: 20567.39
promo_3: 11471.68
mean_4_dow6_2017: 11340.05
day_1_2017: 8527.94
promo_7: 7959.43
promo_60_2017: 7379.28
mean_20_dow6_2017: 7159.96
mean_140_2017: 6873.85
promo_6: 5982.82
promo_140_2017: 5433.88
mean_4_dow0_2017: 4306.57
mean_20_dow3_2017: 4036.87
mean_20_dow2_2017: 3773.69
mean_20_dow0_2017: 3663.21
mean_4_dow3_2017: 3534.50
mean_4_dow2_2017: 3509.46
mean_20_dow4_2017: 3402.02
mean_4_dow1_2017: 3255.09
mean_4_dow4_2017: 3138.01
mean_20_dow1_2017: 2875.65
promo_2: 2794.86
promo_4: 2496.48
promo_0: 2481.84
promo_9: 1908.52
promo_14: 1358.92
promo_1: 1331.82
promo_13: 1242.60
promo_8: 922.43
promo_11: 847.01
promo_12: 777.91
promo_10: 735.21
promo_15: 662.78
==================================================
Step 7
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.346386	valid_1's l2: 0.421888
[200]	training's l2: 0.342067	valid_1's l2: 0.421114
Early stopping, best iteration is:
[186]	training's l2: 0.342512	valid_1's l2: 0.421002
mean_14_2017: 1243780.96
mean_30_2017: 841596.27
mean_7_2017: 480932.80
mean_3_2017: 148359.91
mean_20_dow6_2017: 147155.21
promo_6: 127538.68
mean_4_dow6_2017: 126912.26
mean_60_2017: 110009.44
promo_14_2017: 20754.08
day_1_2017: 12325.09
promo_3: 11377.47
mean_20_dow5_2017: 9391.17
promo_7: 9280.72
promo_60_2017: 6984.13
mean_4_dow5_2017: 6492.02
promo_140_2017: 4736.44
promo_5: 4575.44
mean_20_dow1_2017: 3982.92
mean_140_2017: 3622.33
promo_13: 3439.91
mean_20_dow0_2017: 3104.61
promo_0: 2604.94
mean_4_dow0_2017: 2521.31
promo_4: 2490.91
promo_9: 2319.15
mean_20_dow3_2017: 2283.22
mean_4_dow1_2017: 2255.72
promo_14: 1784.45
mean_20_dow4_2017: 1625.53
mean_4_dow2_2017: 1606.48
mean_20_dow2_2017: 1371.07
mean_4_dow3_2017: 1340.81
promo_1: 1286.62
promo_2: 1208.28
promo_15: 1097.97
mean_4_dow4_2017: 1062.32
promo_8: 747.82
promo_11: 492.28
promo_12: 472.36
promo_10: 304.02
==================================================
Step 8
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.332776	valid_1's l2: 0.390509
[200]	training's l2: 0.328352	valid_1's l2: 0.389465
[300]	training's l2: 0.325422	valid_1's l2: 0.388887
Early stopping, best iteration is:
[290]	training's l2: 0.325679	valid_1's l2: 0.388829
mean_30_2017: 1201964.21
mean_14_2017: 1028752.48
mean_7_2017: 631736.02
promo_7: 181055.15
mean_20_dow0_2017: 166695.94
mean_60_2017: 101867.27
mean_4_dow0_2017: 62267.16
promo_0: 24167.16
mean_3_2017: 22333.58
day_1_2017: 20315.18
promo_14_2017: 12654.90
promo_60_2017: 12260.57
promo_14: 10629.66
promo_140_2017: 8703.18
mean_140_2017: 6946.96
mean_20_dow2_2017: 5814.33
promo_3: 5521.36
mean_20_dow4_2017: 4852.29
promo_6: 3354.94
promo_5: 3303.65
mean_4_dow5_2017: 2748.54
mean_20_dow1_2017: 2625.70
mean_4_dow6_2017: 2596.63
mean_20_dow3_2017: 2466.75
mean_4_dow2_2017: 2366.90
promo_9: 2309.80
mean_4_dow3_2017: 2247.99
mean_4_dow1_2017: 2219.77
mean_20_dow6_2017: 2127.18
promo_4: 1978.55
mean_20_dow5_2017: 1699.05
promo_15: 1674.96
promo_2: 1619.25
mean_4_dow4_2017: 1607.91
promo_10: 1048.61
promo_11: 1042.84
promo_13: 1037.36
promo_8: 904.23
promo_1: 596.22
promo_12: 392.20
==================================================
Step 9
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.341981	valid_1's l2: 0.380455
[200]	training's l2: 0.337788	valid_1's l2: 0.379549
[300]	training's l2: 0.334999	valid_1's l2: 0.379461
Early stopping, best iteration is:
[255]	training's l2: 0.336109	valid_1's l2: 0.379302
mean_30_2017: 1089082.21
mean_14_2017: 718535.28
mean_7_2017: 483356.40
mean_60_2017: 290288.40
promo_8: 103626.07
mean_20_dow1_2017: 85583.25
mean_4_dow1_2017: 25981.47
promo_10: 18820.49
promo_14_2017: 17039.78
day_1_2017: 16583.66
mean_3_2017: 10887.17
promo_60_2017: 10650.51
mean_20_dow2_2017: 9151.52
promo_7: 7810.04
mean_20_dow4_2017: 4896.39
promo_140_2017: 4819.54
mean_140_2017: 4040.74
promo_11: 3895.99
mean_4_dow0_2017: 3748.01
promo_9: 3376.15
promo_12: 3343.02
promo_13: 2786.76
mean_20_dow0_2017: 2752.60
mean_4_dow6_2017: 2650.16
promo_0: 2367.25
mean_4_dow2_2017: 2334.78
mean_20_dow6_2017: 2001.16
mean_20_dow5_2017: 1867.17
promo_3: 1787.26
mean_4_dow5_2017: 1761.65
mean_4_dow3_2017: 1640.13
mean_4_dow4_2017: 1601.28
promo_14: 1372.28
promo_6: 1186.78
mean_20_dow3_2017: 946.32
promo_4: 898.04
promo_15: 545.36
promo_5: 475.13
promo_2: 449.78
promo_1: 425.27
==================================================
Step 10
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.346186	valid_1's l2: 0.369176
[200]	training's l2: 0.341413	valid_1's l2: 0.368133
[300]	training's l2: 0.338341	valid_1's l2: 0.36774
Early stopping, best iteration is:
[334]	training's l2: 0.337405	valid_1's l2: 0.367624
mean_30_2017: 1068407.05
mean_14_2017: 851111.48
mean_7_2017: 441846.57
mean_20_dow2_2017: 367277.02
mean_4_dow2_2017: 331142.37
mean_60_2017: 140804.95
promo_9: 127274.08
promo_14_2017: 22554.40
promo_10: 14191.27
promo_140_2017: 12790.94
promo_2: 12423.12
mean_3_2017: 11453.24
promo_7: 8993.01
promo_60_2017: 8569.76
mean_20_dow4_2017: 7641.01
day_1_2017: 7489.42
mean_4_dow1_2017: 6335.35
mean_20_dow1_2017: 6084.17
promo_8: 5952.63
promo_14: 4554.13
mean_140_2017: 4141.20
mean_4_dow0_2017: 4132.97
mean_20_dow5_2017: 3898.14
mean_20_dow0_2017: 3626.76
promo_11: 3477.64
mean_4_dow3_2017: 3473.04
promo_12: 3395.19
mean_20_dow6_2017: 2553.92
promo_13: 2521.07
mean_20_dow3_2017: 2454.26
mean_4_dow4_2017: 2160.50
mean_4_dow5_2017: 2121.35
mean_4_dow6_2017: 2101.12
promo_0: 1223.35
promo_4: 1159.36
promo_6: 1077.48
promo_1: 1074.34
promo_15: 875.22
promo_3: 356.78
promo_5: 343.94
==================================================
Step 11
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.374217	valid_1's l2: 0.374343
[200]	training's l2: 0.369242	valid_1's l2: 0.37313
[300]	training's l2: 0.365801	valid_1's l2: 0.37264
Early stopping, best iteration is:
[297]	training's l2: 0.365903	valid_1's l2: 0.37263
mean_30_2017: 1551792.05
mean_14_2017: 733009.73
mean_7_2017: 620589.12
mean_60_2017: 376812.11
mean_4_dow3_2017: 269880.41
mean_20_dow3_2017: 186580.98
promo_10: 105770.64
mean_3_2017: 18917.14
promo_14_2017: 16382.48
mean_4_dow2_2017: 14346.23
mean_4_dow4_2017: 13566.76
promo_60_2017: 10608.32
mean_140_2017: 8141.54
promo_140_2017: 7533.87
promo_14: 6980.84
promo_7: 5815.12
promo_11: 5514.66
promo_9: 5462.64
day_1_2017: 5317.44
mean_20_dow0_2017: 4906.11
promo_12: 4760.65
mean_20_dow5_2017: 4759.42
promo_13: 4270.91
mean_20_dow4_2017: 3803.63
mean_20_dow2_2017: 3452.98
mean_20_dow6_2017: 3081.05
promo_8: 3006.98
mean_4_dow0_2017: 2709.99
mean_20_dow1_2017: 2517.74
promo_3: 2449.65
mean_4_dow1_2017: 2328.97
mean_4_dow6_2017: 1813.58
mean_4_dow5_2017: 1691.13
promo_0: 1366.22
promo_15: 1185.14
promo_6: 1105.62
promo_2: 798.17
promo_4: 560.62
promo_5: 377.87
promo_1: 243.60
==================================================
Step 12
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.384713	valid_1's l2: 0.386644
[200]	training's l2: 0.379179	valid_1's l2: 0.384911
[300]	training's l2: 0.375363	valid_1's l2: 0.384537
[400]	training's l2: 0.372432	valid_1's l2: 0.384373
[500]	training's l2: 0.369803	valid_1's l2: 0.384382
Did not meet early stopping. Best iteration is:
[500]	training's l2: 0.369803	valid_1's l2: 0.384382
mean_4_dow4_2017: 1370982.32
mean_30_2017: 1355250.45
mean_14_2017: 462550.81
mean_20_dow4_2017: 278526.43
mean_60_2017: 217485.42
mean_7_2017: 208292.14
mean_3_2017: 127307.94
promo_11: 94459.64
mean_4_dow3_2017: 21026.97
promo_14_2017: 15943.77
promo_12: 14205.25
promo_14: 11600.03
promo_140_2017: 10162.97
promo_10: 9071.29
promo_60_2017: 8552.60
mean_140_2017: 7666.43
promo_13: 7163.15
promo_9: 6089.75
mean_20_dow0_2017: 5746.46
promo_4: 5438.72
day_1_2017: 5411.00
mean_20_dow3_2017: 5172.14
promo_7: 5090.21
mean_20_dow1_2017: 4617.93
mean_20_dow6_2017: 4442.93
mean_20_dow2_2017: 4200.04
mean_4_dow0_2017: 4021.92
mean_20_dow5_2017: 3742.36
promo_8: 3434.41
mean_4_dow1_2017: 3301.63
mean_4_dow5_2017: 3271.57
mean_4_dow6_2017: 3104.68
mean_4_dow2_2017: 2991.24
promo_0: 1721.87
promo_15: 1267.68
promo_6: 1040.03
promo_2: 809.52
promo_5: 603.10
promo_1: 574.65
promo_3: 421.10
==================================================
Step 13
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.370391	valid_1's l2: 0.377167
[200]	training's l2: 0.365673	valid_1's l2: 0.376426
[300]	training's l2: 0.362355	valid_1's l2: 0.376125
Early stopping, best iteration is:
[313]	training's l2: 0.36202	valid_1's l2: 0.376111
mean_30_2017: 1512113.21
mean_14_2017: 667690.26
mean_60_2017: 408090.65
mean_7_2017: 295232.27
mean_3_2017: 141902.71
promo_12: 94060.98
mean_20_dow5_2017: 90786.83
mean_4_dow5_2017: 60874.53
promo_13: 20799.36
promo_14_2017: 15518.11
promo_14: 12691.85
promo_10: 10871.85
promo_60_2017: 9400.67
mean_140_2017: 8894.87
day_1_2017: 8119.50
mean_20_dow0_2017: 6735.48
promo_140_2017: 5912.49
mean_20_dow6_2017: 5029.68
mean_4_dow6_2017: 4268.58
promo_9: 3851.51
mean_20_dow3_2017: 3596.09
mean_20_dow2_2017: 3456.20
promo_11: 3284.56
mean_4_dow0_2017: 3204.52
promo_15: 2573.04
mean_4_dow3_2017: 2559.82
mean_20_dow1_2017: 2558.03
mean_4_dow2_2017: 2546.10
mean_4_dow4_2017: 2376.98
mean_20_dow4_2017: 2230.21
promo_7: 1994.93
mean_4_dow1_2017: 1994.88
promo_8: 1795.99
promo_0: 1530.59
promo_5: 1360.51
promo_6: 1152.89
promo_3: 877.18
promo_4: 684.51
promo_2: 550.83
promo_1: 448.69
==================================================
Step 14
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.359665	valid_1's l2: 0.361825
[200]	training's l2: 0.355192	valid_1's l2: 0.361163
[300]	training's l2: 0.35227	valid_1's l2: 0.361076
[400]	training's l2: 0.349697	valid_1's l2: 0.361016
Early stopping, best iteration is:
[368]	training's l2: 0.350439	valid_1's l2: 0.360975
mean_30_2017: 1482232.95
mean_14_2017: 459224.30
mean_7_2017: 367831.54
mean_60_2017: 245569.01
mean_20_dow6_2017: 221554.05
promo_13: 161975.16
mean_3_2017: 86807.29
mean_4_dow6_2017: 82731.05
day_1_2017: 23805.73
promo_14_2017: 17552.75
mean_4_dow5_2017: 12917.88
mean_140_2017: 10253.92
mean_20_dow5_2017: 9770.89
promo_14: 9692.89
promo_60_2017: 9524.53
promo_10: 8752.34
mean_20_dow1_2017: 7382.94
promo_140_2017: 7194.28
mean_20_dow0_2017: 6909.18
promo_6: 6611.18
promo_12: 4948.72
mean_4_dow0_2017: 3718.80
mean_20_dow4_2017: 3353.35
mean_20_dow3_2017: 3341.43
promo_0: 3257.34
mean_4_dow1_2017: 3163.89
promo_9: 2917.21
mean_4_dow3_2017: 2658.16
promo_11: 2633.21
mean_4_dow2_2017: 2524.51
mean_20_dow2_2017: 2373.91
mean_4_dow4_2017: 2017.83
promo_15: 1898.88
promo_8: 1529.34
promo_7: 1448.79
promo_2: 804.65
promo_4: 662.75
promo_1: 581.12
promo_3: 384.99
promo_5: 300.02
==================================================
Step 15
==================================================
Training until validation scores don't improve for 50 rounds.
[100]	training's l2: 0.346914	valid_1's l2: 0.349081
[200]	training's l2: 0.342417	valid_1's l2: 0.347809
[300]	training's l2: 0.339408	valid_1's l2: 0.347388
[400]	training's l2: 0.336847	valid_1's l2: 0.347235
Early stopping, best iteration is:
[427]	training's l2: 0.336255	valid_1's l2: 0.347195
mean_30_2017: 1569373.91
mean_14_2017: 662872.33
mean_7_2017: 361059.28
mean_20_dow0_2017: 267898.04
promo_14: 198143.06
mean_60_2017: 163088.22
mean_4_dow0_2017: 51240.99
promo_14_2017: 17924.56
mean_3_2017: 15967.32
promo_7: 15847.49
day_1_2017: 14577.64
promo_140_2017: 12747.43
promo_0: 12459.05
promo_60_2017: 11653.14
mean_20_dow2_2017: 11026.20
promo_13: 10202.53
mean_140_2017: 6755.47
mean_20_dow4_2017: 6329.32
promo_12: 5753.18
promo_10: 5519.02
mean_20_dow1_2017: 4844.63
mean_4_dow2_2017: 3608.41
mean_4_dow5_2017: 3531.43
promo_9: 3453.74
mean_4_dow6_2017: 3393.84
mean_20_dow3_2017: 3360.07
promo_15: 3342.76
mean_20_dow6_2017: 3317.12
mean_4_dow1_2017: 2905.05
mean_20_dow5_2017: 2857.02

In [37]:
print("Validation mse:", mean_squared_error(
    y_val, np.array(val_pred).transpose()))

('Validation mse:', 0.36243283304926488)

In [38]:
y_test = np.array(test_pred).transpose()
df_preds = pd.DataFrame(
    y_test, index=df_2017.index,
    columns=pd.date_range("2017-08-16", periods=16)
).stack().to_frame("unit_sales")
df_preds.index.set_names(["store_nbr", "item_nbr", "date"], inplace=True)

In [39]:
submission = df_test[["id"]].join(df_preds, how="left").fillna(0)
submission["unit_sales"] = np.clip(np.expm1(submission["unit_sales"]), 0, 1000)
submission.to_csv('lgb.csv', float_format='%.4f', index=None)

In [1]:
import pandas as pd

In [22]:
submit = pd.read_csv("lgb.csv")

In [26]:
from datetime import date

In [31]:
pd.date_range(start = date(2017,1,1),end = date(2017,2,28))

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
               '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16',
               '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20',
               '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24',
               '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28',
               '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01',
               '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05',
               '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09',
               '2017-02-10', '2017-02-11', '2017-02-12', '2017-02-13',
               '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17',
               '2017-02-18', '2017-02-19', '2017-02-20', '2017-02-21',
               '2017-02-22', '2017-02-23', '2017-02-24', '2017-02-25',
               '2017-02-26', '2017-02-27', '2017-02-28'],
              dtype='datetime64[ns]', freq='D')

In [33]:
t2017 = date(2017, 5, 31)

In [36]:
from datetime import timedelta

In [39]:
pd.date_range(t2017-timedelta(days=28),periods=6,freq="7D")

DatetimeIndex(['2017-05-03', '2017-05-10', '2017-05-17', '2017-05-24',
               '2017-05-31', '2017-06-07'],
              dtype='datetime64[ns]', freq='7D')